language: python
install: pip install -r requirements_dev.txt
matrix:
  include:
  - python: 3.6
    env:
    - TOX_ENV=py36
  - python: 3.7
    env:
    - TOX_ENV=py37
    dist: xenial
script: tox -e $TOX_ENV
deploy:
  provider: pypi
  user: "weitzner"
  password:
    secure: nSrl569Oodt0zdkQThsM/3K/kpmIkxencW2Ov8zrkpk04vLP5wwWneYHOUlob/kDNxc8Xwvy1wWMnRXEYZw39g/A3DnbQiBYJF220TOznZQHmFxHp7WmDlfgYJD4/1+ClouwtFIdSQaiFde3OIxS+tLK+sf/LJo6M8gmmLA+D1UBk0Xg95nBTRyaRPuHFxish+B8ZO0ZSR6f+f4gLPfM7bVJDMoTdY8GmlhtIO52NVdmMcLWjymecgMRjkVhDqY46P3JWCGyQZnZxhX3VU0zurPequLJbPtUg+BJN6EJAKpdDRe1ccC06cN3881YWBaCAvBmXO7QZxuz9gfGOnjwFQ8ydTNpY7wi2ahFnxb/BflKgTGgdJyfyuduZF8vYZDv4ktfqusUNAnQGIjRueOWMGYW4dQEiBtzwi3ZYJafsN36PFJxAnP6mvlJQN1u0T64RUeF6hfLLu8guR2o0nVAw+3N3Nve0mZ7bxs2PF8uzPdysfAPtmw0+r/XAeqtC0nQhl2TrkGnlwhlmLBNhkowy8YOEPNjghVbzzZxcFiRfTIxi6b5rBQcm6ARMVKRsIQ8d9f2r+S+hbtARyqWhSd6tkjGfnpPjCPwe1ewqDCUdCfIuIjMNdXcQz3f/Y6Mlen8+oN+/WkPSl/NoS8RYXP+N1CqyDz05eReOvyEkTpU0eE=
  on:
    tags: true
    condition: $TOX_ENV = py36
