# Config file for automatic testing at travis-ci.org

language: python

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_dev.txt

matrix:
  include:
    - python: 3.5
      env:
       - TOX_ENV=py35
    - python: 3.6
      env:
        - TOX_ENV=py36

# Command to run tests, e.g. python setup.py test
script: tox -e $TOX_ENV


